### ISSUE TITLE
iOS Training: Assignment 1: Temperature Converter: Submission

### ISSUE THREAD

**Issue by ambikasam** [ambikasam/tempature-converter#1]
Hi,

Submitting iOS Training week 1 assignments.
Temperature Coverter.

Thanks,
Ambika
/cc @nesquena @timothy1ee

**Comment by timothy1ee** [comment]
Great, looks good.  Instead of using `@property(nonatomic, strong) NSString *selectedField`, consider using something like `@property (nonatomic, strong) UITextField *selectedField`.  That way, you don't have to rely on a particular placeholder text.

**Comment by ambikasam** [comment]
Thank you.
